# Generated by Django 3.1.3 on 2021-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('purpose', models.BooleanField(default=False)),
                ('belong', models.CharField(default=None, max_length=300)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
