# Generated by Django 3.1.3 on 2021-12-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='nickname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
