# Generated by Django 3.1.3 on 2021-12-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211228_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='nickname',
            field=models.CharField(default='익명', max_length=100, unique=True),
        ),
    ]
