# Generated by Django 3.1.3 on 2021-12-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20211228_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='nickname',
            field=models.CharField(default='익명4', max_length=100, unique=True),
        ),
    ]
