# Generated by Django 3.1.3 on 2021-12-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20211228_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
