# Generated by Django 3.2.4 on 2021-12-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_custom_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
