# Generated by Django 3.1.3 on 2021-12-28 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('still_ing', models.BooleanField(default=True)),
                ('dday', models.CharField(max_length=100)),
                ('members', models.IntegerField(default=0)),
                ('part', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=300)),
                ('detail', models.TextField(null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='nickname')),
            ],
        ),
    ]
